import Head from "next/head";
import Header from "components/Header";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Evan Fetherolf | Video Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <div className={`container`}>
        <Header />
        {children}
      </div>
    </>
  );
};

export default Layout;
